import type { Post } from '@/types/community'

const now = new Date('2026-08-12T09:00:00Z')

export const BOOKMARKED_POSTS: Post[] = [
  {
    id: 'history-bookmark-1',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-brian', displayName: 'Brian Lee', handle: '@brianlee' },
    content: 'Exploring the latest trends in sustainable investing. How green is your portfolio? 🌱',
    isAnonymous: false,
    isPinned: false,
    likeCount: 98,
    replyCount: 14,
    repostCount: 3,
    hasBookmarked: true,
    timeAgo: '1h',
    tags: ['Invest'],
    replierAvatars: [
      'https://picsum.photos/seed/history-invest-1/80/80',
      'https://picsum.photos/seed/history-invest-2/80/80',
    ],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'history-bookmark-2',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-maya', displayName: 'Maya Patel', handle: '@mayapatel' },
    content: 'Breaking down the myths about cryptocurrency and what you really need to know before diving in.',
    isAnonymous: false,
    isPinned: false,
    likeCount: 157,
    replyCount: 39,
    repostCount: 8,
    hasBookmarked: true,
    timeAgo: '45m',
    tags: ['Crypto'],
    replierAvatars: [
      'https://picsum.photos/seed/history-crypto-1/80/80',
      'https://picsum.photos/seed/history-crypto-2/80/80',
    ],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'history-bookmark-3',
    channelId: 'circle-entrepreneurship',
    channelName: 'Entrepreneurship',
    author: { id: 'u-liam', displayName: 'Liam Chen', handle: '@liamchen' },
    content: 'Exploring sustainable fashion trends and how brands are adopting eco-friendly practices. 🌿',
    isAnonymous: false,
    isPinned: false,
    likeCount: 89,
    replyCount: 24,
    repostCount: 5,
    hasBookmarked: true,
    timeAgo: '2h',
    tags: ['Sustainability'],
    replierAvatars: [
      'https://picsum.photos/seed/history-fashion-1/80/80',
      'https://picsum.photos/seed/history-fashion-2/80/80',
    ],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
]

export const VIDEO_POSTS: Post[] = [
  {
    ...BOOKMARKED_POSTS[0],
    id: 'history-video-1',
    attachments: [{ id: 'video-1', type: 'video', url: '' }],
  },
  {
    ...BOOKMARKED_POSTS[0],
    id: 'history-video-2',
    attachments: [{ id: 'video-2', type: 'video', url: '' }],
  },
]

export const LIKED_POSTS: Post[] = [
  {
    id: 'history-like-1',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-brian', displayName: 'Brian Lee', handle: '@brianlee' },
    content: 'Exploring the latest trends in sustainable investing. How green is your portfolio? 🌱',
    isAnonymous: false,
    isPinned: false,
    likeCount: 98,
    replyCount: 14,
    repostCount: 3,
    hasLiked: true,
    timeAgo: '1h',
    tags: ['Invest'],
    replierAvatars: [
      'https://picsum.photos/seed/history-invest-1/80/80',
      'https://picsum.photos/seed/history-invest-2/80/80',
    ],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'history-like-2',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-sophia', displayName: 'Sophia Martinez', handle: '@sophiamartinez' },
    content: 'Just wrapped up an inspiring webinar on renewable energy innovations. The future looks bright.',
    isAnonymous: false,
    isPinned: false,
    likeCount: 120,
    replyCount: 20,
    repostCount: 6,
    hasLiked: true,
    timeAgo: '2h',
    tags: ['RenewableEnergy'],
    replierAvatars: [
      'https://picsum.photos/seed/history-energy-1/80/80',
      'https://picsum.photos/seed/history-energy-2/80/80',
    ],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'history-like-3',
    channelId: 'circle-entrepreneurship',
    channelName: 'Entrepreneurship',
    author: { id: 'u-david', displayName: 'David Kim', handle: '@davidkim' },
    content: 'Diving into the world of ethical fashion. Can style and sustainability coexist? 👗🌱',
    isAnonymous: false,
    isPinned: false,
    likeCount: 75,
    replyCount: 8,
    repostCount: 2,
    hasLiked: true,
    timeAgo: '3h',
    tags: ['FashionTech'],
    replierAvatars: [
      'https://picsum.photos/seed/history-fashiontech-1/80/80',
      'https://picsum.photos/seed/history-fashiontech-2/80/80',
    ],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
]
