import type { Circle } from '@/types/circles'
import type { Post } from '@/types/community'

const now = new Date('2026-08-12T09:00:00Z')

export const MOCK_COMMUNITIES: Circle[] = [
  {
    id: 'circle-wealth',
    name: 'Wealth Building',
    slug: 'wealth-building',
    emoji: '💰',
    category: 'Business',
    memberCount: 3900,
    isPrivate: false,
    requiresApproval: false,
    isLeader: false,
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'circle-entrepreneurship',
    name: 'Entrepreneurship',
    slug: 'entrepreneurship',
    emoji: '🚀',
    category: 'Business',
    memberCount: 3900,
    isPrivate: false,
    requiresApproval: false,
    isLeader: false,
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'circle-career',
    name: 'Career Growth',
    slug: 'career-growth',
    emoji: '📈',
    category: 'Career',
    memberCount: 2100,
    isPrivate: false,
    requiresApproval: false,
    isLeader: false,
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
]

export const FOR_YOU_POSTS: Post[] = [
  {
    id: 'post-1',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-brian', displayName: 'Brian Lee', handle: '@brianlee' },
    content: 'Exploring the latest trends in sustainable investing. How green is your portfolio? 🌱',
    isAnonymous: false,
    isPinned: false,
    likeCount: 98,
    replyCount: 14,
    repostCount: 3,
    timeAgo: '1h',
    tags: ['Invest'],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'post-2',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    isAnonymous: true,
    anonymousHandle: 'Anonymous Sister',
    content: 'Breaking down the myths about cryptocurrency and what you really need to know before diving in.',
    isPinned: false,
    likeCount: 157,
    replyCount: 39,
    repostCount: 8,
    timeAgo: '33m',
    tags: ['Crypto'],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'post-3',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-brian', displayName: 'Brian Lee', handle: '@brianlee' },
    content: "Here's a quick recap from today's investing workshop 📊",
    isAnonymous: false,
    isPinned: false,
    likeCount: 42,
    replyCount: 6,
    repostCount: 1,
    timeAgo: '1h',
    tags: ['Invest'],
    attachments: [{ id: 'att-1', type: 'image', url: '' }],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
]

export const MY_POSTS: Post[] = [
  {
    id: 'my-post-1',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    author: { id: 'u-amy', displayName: 'Amy Lee', handle: '@amylee' },
    content: 'Exploring the latest trends in sustainable investing. How green is your portfolio? 🌱',
    isAnonymous: false,
    isPinned: false,
    likeCount: 98,
    replyCount: 14,
    repostCount: 3,
    timeAgo: '1h',
    tags: ['Invest'],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'my-post-2',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    isAnonymous: true,
    anonymousHandle: 'Anonymous',
    content: 'Breaking down the myths about cryptocurrency and what you really need to know before diving in.',
    isPinned: false,
    likeCount: 0,
    replyCount: 0,
    repostCount: 0,
    timeAgo: '33m',
    tags: ['Crypto'],
    moderationStatus: 'pending',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'my-post-3',
    channelId: 'circle-entrepreneurship',
    channelName: 'Entrepreneurship',
    isAnonymous: true,
    anonymousHandle: 'Anonymous',
    content: '5 side hustles that actually pay in 2026 💼',
    isPinned: false,
    likeCount: 157,
    replyCount: 39,
    repostCount: 12,
    timeAgo: '2h',
    tags: ['SideHustle'],
    moderationStatus: 'approved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'my-post-4',
    channelId: 'circle-wealth',
    channelName: 'Wealth Building',
    isAnonymous: true,
    anonymousHandle: 'Anonymous',
    content: 'Breaking down the myths about cryptocurrency and what you really need to know before diving in.',
    isPinned: false,
    likeCount: 0,
    replyCount: 0,
    repostCount: 0,
    timeAgo: '33m',
    tags: ['Crypto'],
    moderationStatus: 'rejected',
    rejectionReason:
      "This post included content that isn't allowed in this space. Our admins review every post to keep things safe and on-topic.",
    createdAt: now,
    updatedAt: now,
  },
]
