import { colors } from '@/theme/colors'
import type { Channel, Post } from '@/types/community'

export const CATEGORIES = ['All', 'Finance', 'Business', 'Networking', 'Social']

export const CATEGORY_STYLE: Record<string, { gradient: [string, string]; emoji: string }> = {
  Finance: { gradient: [colors.light.primary[400], colors.light.primary[800]], emoji: '💰' },
  Business: { gradient: [colors.light.tertiary[400], colors.light.tertiary[800]], emoji: '🚀' },
  Networking: { gradient: [colors.light.secondary[400], colors.light.secondary[700]], emoji: '📈' },
  Social: { gradient: [colors.light.tertiary[400], colors.light.primary[700]], emoji: '👭' },
}

const now = new Date('2026-08-11T09:00:00Z')

export const SPACES: Channel[] = [
  {
    id: 'wealth-building',
    name: 'Wealth Building',
    slug: 'wealth-building',
    emoji: '💰',
    category: 'Finance',
    tagline: 'Stewardship, abundance, and financial freedom',
    description:
      'A space for honest conversations about money — budgeting, investing, and building lasting wealth without shame or judgment.',
    guidelines: [
      'Be respectful and supportive of fellow builders.',
      'Stay on topic — investing, budgeting, and financial growth.',
      'No spam or unsolicited promotions.',
      'Encourage honest, constructive discussions.',
    ],
    isPrivate: false,
    memberCount: 5200,
    unreadCount: 0,
    pinnedPostIds: [],
    memberAvatars: ['AM', 'BL', 'MP', 'CR'],
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'entrepreneurship',
    name: 'Entrepreneurship',
    slug: 'entrepreneurship',
    emoji: '🚀',
    category: 'Business',
    tagline: 'Building, launching, and scaling on your own terms',
    description:
      'For women building businesses from the ground up — swap wins, lessons, and honest talk about the hard parts of founding something.',
    guidelines: [
      'Be respectful and supportive of fellow founders.',
      'Stay on topic — business, operations, and growth.',
      'No spam or unsolicited promotions.',
      'Encourage honest, constructive discussions.',
    ],
    isPrivate: false,
    memberCount: 3900,
    unreadCount: 0,
    pinnedPostIds: [],
    memberAvatars: ['DT', 'JN', 'RK', 'SA'],
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'career-development',
    name: 'Career Development',
    slug: 'career-development',
    emoji: '📈',
    category: 'Networking',
    tagline: 'Leveling up your career, one connection at a time',
    description:
      'Career moves, negotiation wins, mentorship, and the network that gets you into the room. Come learn and share what got you here.',
    guidelines: [
      'Be respectful and supportive of fellow members.',
      'Stay on topic — careers, mentorship, and networking.',
      'No spam or unsolicited promotions.',
      'Encourage honest, constructive discussions.',
    ],
    isPrivate: false,
    memberCount: 6100,
    unreadCount: 0,
    pinnedPostIds: [],
    memberAvatars: ['TA', 'AK', 'FO', 'LB'],
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'connections',
    name: 'Connections',
    slug: 'connections',
    emoji: '👭',
    category: 'Social',
    tagline: 'Friendship, community, and showing up for each other',
    description:
      'A space for honest conversations about the people in our lives — family, friendship, and the art of maintaining meaningful community.',
    guidelines: [
      'Be respectful and supportive of fellow sisters.',
      'Stay on topic — friendship, community, and connection.',
      'No spam or unsolicited promotions.',
      'Encourage honest, constructive discussions.',
    ],
    isPrivate: false,
    memberCount: 2700,
    unreadCount: 0,
    pinnedPostIds: [],
    memberAvatars: ['NC', 'PW', 'ZH', 'EO'],
    lastActivityAt: now,
    createdAt: now,
    updatedAt: now,
  },
]

export const SPACE_POSTS: Record<string, Post[]> = {
  'wealth-building': [
    {
      id: 'post-1',
      channelId: 'wealth-building',
      channelName: 'Wealth Building',
      author: { id: 'u1', displayName: 'Aisha Aminu', handle: '@aishaa' },
      content: "Let's talk about the incredible power of perseverance and how it can change your life 🚀",
      isAnonymous: false,
      isPinned: true,
      likeCount: 112,
      replyCount: 26,
      repostCount: 4,
      timeAgo: '33m',
      moderationStatus: 'approved',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'post-2',
      channelId: 'wealth-building',
      channelName: 'Wealth Building',
      author: { id: 'u2', displayName: 'Brian Lee', handle: '@brianlee' },
      content: 'Exploring the latest trends in sustainable investing. How green is your portfolio? 🌱',
      isAnonymous: false,
      isPinned: false,
      likeCount: 98,
      replyCount: 14,
      repostCount: 2,
      timeAgo: '1h',
      moderationStatus: 'approved',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'post-3',
      channelId: 'wealth-building',
      channelName: 'Wealth Building',
      author: { id: 'u3', displayName: 'Maya Patel', handle: '@mayap' },
      content: 'Breaking down the myths about cryptocurrency and what you really need to know before diving in',
      isAnonymous: false,
      isPinned: false,
      likeCount: 157,
      replyCount: 39,
      repostCount: 6,
      timeAgo: '45m',
      moderationStatus: 'approved',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'post-4',
      channelId: 'wealth-building',
      channelName: 'Wealth Building',
      author: { id: 'u4', displayName: 'Carlos Ramirez', handle: '@carlosr' },
      content: 'How budgeting apps can simplify your life and boost your savings habits. Have you tried any? 📱',
      isAnonymous: false,
      isPinned: false,
      likeCount: 84,
      replyCount: 21,
      repostCount: 3,
      timeAgo: '27m',
      moderationStatus: 'approved',
      createdAt: now,
      updatedAt: now,
    },
  ],
}
