import type { MemberProfile } from '@/types/members'
import { CATEGORIES } from '@/components/community/spaces.data'

export { CATEGORIES }

const now = new Date('2026-08-15T09:00:00Z')

function makeMember(
  member: Partial<MemberProfile> & Pick<MemberProfile, 'id' | 'displayName' | 'handle'>,
): MemberProfile {
  return {
    interests: [],
    joinedAt: now,
    isOnline: false,
    isVerified: false,
    membershipTier: 'free',
    circlesCount: 0,
    followerCount: 0,
    followingCount: 0,
    joinedSpaceIds: [],
    createdAt: now,
    updatedAt: now,
    ...member,
  }
}

const MUTUAL_AVATARS = [
  'https://picsum.photos/seed/mutual-1/60/60',
  'https://picsum.photos/seed/mutual-2/60/60',
  'https://picsum.photos/seed/mutual-3/60/60',
]

export const MEMBERS: MemberProfile[] = [
  makeMember({
    id: 'mem-aisha',
    displayName: 'Aisha Bello',
    handle: '@aishab',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Design systems nerd. Building calmer software, one interface at a time.',
    avatarUrl: 'https://picsum.photos/seed/aisha-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/aisha-cover/600/400',
    followerCount: 412,
    followingCount: 189,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['wealth-building', 'connections'],
  }),
  makeMember({
    id: 'mem-tobenna',
    displayName: 'Tobenna Okafor',
    handle: '@tobenna.o',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Visual storyteller. Coffee-fueled Figma sessions and good conversations.',
    avatarUrl: 'https://picsum.photos/seed/tobenna-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/tobenna-cover/600/400',
    followerCount: 530,
    followingCount: 240,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['entrepreneurship'],
  }),
  makeMember({
    id: 'mem-maya',
    displayName: 'Maya Ihenacho',
    handle: '@mayaih',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Crypto-curious, always investing in myself first.',
    avatarUrl: 'https://picsum.photos/seed/maya-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/maya-cover/600/400',
    followerCount: 298,
    followingCount: 150,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['wealth-building', 'career-development'],
  }),
  makeMember({
    id: 'mem-kemi',
    displayName: 'Kemi Adeyemi',
    handle: '@kemi.dey',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Budgeting apps enthusiast. Building generational wealth, slowly and surely.',
    avatarUrl: 'https://picsum.photos/seed/kemi-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/kemi-cover/600/400',
    followerCount: 675,
    followingCount: 320,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['wealth-building'],
  }),
  makeMember({
    id: 'mem-chidera',
    displayName: 'Chidera Nwosu',
    handle: '@chidera_n',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Sustainable investing advocate. Green portfolios only 🌱',
    avatarUrl: 'https://picsum.photos/seed/chidera-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/chidera-cover/600/400',
    followerCount: 401,
    followingCount: 210,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['entrepreneurship', 'connections'],
  }),
  makeMember({
    id: 'mem-ayo',
    displayName: 'Ayo Adebisi',
    handle: '@Ayo',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Entrepreneur at heart. Always building something new.',
    avatarUrl: 'https://picsum.photos/seed/ayo-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/ayo-cover/600/400',
    followerCount: 812,
    followingCount: 305,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['wealth-building', 'entrepreneurship', 'career-development'],
  }),
  makeMember({
    id: 'mem-chiamaka',
    displayName: 'Chiamaka Okafor',
    handle: '@Chiamaka',
    occupation: 'Product Designer',
    location: 'Lekki, Lagos',
    bio: 'Finance by day, community builder by night.',
    avatarUrl: 'https://picsum.photos/seed/chiamaka-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/chiamaka-cover/600/400',
    followerCount: 356,
    followingCount: 198,
    mutualFriendCount: 5,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['career-development'],
  }),
  makeMember({
    id: 'mem-amara-johnson',
    displayName: 'Amara Johnson',
    handle: '@amara.j',
    occupation: 'Tech Lead',
    location: 'Lagos, NG',
    bio: 'Building in community | Tech Lead | Wellness advocate. Obsessed with storytelling, strategy, and sisterhood.',
    avatarUrl: 'https://picsum.photos/seed/amara-johnson-avatar/200/200',
    coverImageUrl: 'https://picsum.photos/seed/amara-johnson-cover/600/400',
    isVerified: true,
    followerCount: 236,
    followingCount: 504,
    mutualFriendCount: 58,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['wealth-building', 'entrepreneurship', 'career-development'],
  }),
  makeMember({
    id: 'mem-temi',
    displayName: 'Temi A.',
    handle: '@temia',
    occupation: 'Product Designer',
    location: 'Lagos',
    coverImageUrl: 'https://picsum.photos/seed/temi-cover/300/200',
    avatarUrl: 'https://picsum.photos/seed/temi-avatar/200/200',
    followerCount: 244,
    followingCount: 120,
    joinedSpaceIds: ['wealth-building'],
  }),
  makeMember({
    id: 'mem-amarak',
    displayName: 'Amara K.',
    handle: '@amarak',
    occupation: 'Finance',
    location: 'Lagos',
    coverImageUrl: 'https://picsum.photos/seed/amara-cover/300/200',
    avatarUrl: 'https://picsum.photos/seed/amara-avatar/200/200',
    followerCount: 190,
    followingCount: 88,
    joinedSpaceIds: ['wealth-building', 'connections'],
  }),
  makeMember({
    id: 'mem-fatima',
    displayName: 'Fatima O.',
    handle: '@fatimao',
    occupation: 'Marketing',
    location: 'Lagos',
    coverImageUrl: 'https://picsum.photos/seed/fatima-cover/300/200',
    avatarUrl: 'https://picsum.photos/seed/fatima-avatar/200/200',
    followerCount: 167,
    followingCount: 102,
    joinedSpaceIds: ['connections'],
  }),
  makeMember({
    id: 'mem-zainab',
    displayName: 'Zainab R.',
    handle: '@zainabr',
    occupation: 'Product Design',
    location: 'Abuja',
    coverImageUrl: 'https://picsum.photos/seed/zainab-cover/300/200',
    avatarUrl: 'https://picsum.photos/seed/zainab-avatar/200/200',
    followerCount: 210,
    followingCount: 140,
    joinedSpaceIds: ['entrepreneurship'],
  }),
  makeMember({
    id: 'mem-ngozi',
    displayName: 'Ngozi Eze',
    handle: '@ngozieze',
    occupation: 'Marketing',
    location: 'Victoria Island, Lagos',
    coverImageUrl: 'https://picsum.photos/seed/ngozi-cover/300/200',
    avatarUrl: 'https://picsum.photos/seed/ngozi-avatar/200/200',
    followerCount: 145,
    followingCount: 96,
    mutualFriendCount: 3,
    mutualFriendAvatars: MUTUAL_AVATARS.slice(0, 2),
    joinedSpaceIds: ['career-development'],
  }),
  makeMember({
    id: 'mem-blessing',
    displayName: 'Blessing Danjuma',
    handle: '@blessingd',
    occupation: 'Entrepreneur',
    location: 'Abuja',
    coverImageUrl: 'https://picsum.photos/seed/blessing-cover/300/200',
    avatarUrl: 'https://picsum.photos/seed/blessing-avatar/200/200',
    followerCount: 289,
    followingCount: 175,
    mutualFriendCount: 7,
    mutualFriendAvatars: MUTUAL_AVATARS,
    joinedSpaceIds: ['entrepreneurship', 'wealth-building'],
  }),
]

export function findMember(id: string) {
  return MEMBERS.find(member => member.id === id)
}

export function getMembersByIds(ids: string[]) {
  return ids.map(findMember).filter((member): member is MemberProfile => !!member)
}

export const NEARBY_MEMBERS = getMembersByIds(['mem-temi', 'mem-amarak', 'mem-fatima', 'mem-zainab'])
export const SUGGESTED_MEMBERS = getMembersByIds(['mem-ayo', 'mem-chiamaka', 'mem-ngozi', 'mem-blessing'])

export const SEARCH_SUGGESTED_IDS = ['mem-temi', 'mem-amarak', 'mem-fatima']
export const SISTERHOOD_IDS = ['mem-aisha', 'mem-tobenna', 'mem-maya', 'mem-kemi', 'mem-chidera', 'mem-ayo', 'mem-chiamaka']
